Repository vitrivr/cineast, pull requests merged in 2022-10, with the labels that each got.

#345 Respecting Config Flag for CLI
  cineast-api/src/main/java/org/vitrivr/cineast/api/Main.java
  cineast.json
Labels: waiting-for-approval

#343 Switch from deprecated openjdk to eclipse-temurin base
  Dockerfile
Labels: waiting-for-approval

#334 Fix Parallel Execution of CLIP Feature
  build.gradle
  cineast-api/build.gradle
  cineast-api/src/main/java/org/vitrivr/cineast/api/websocket/handlers/queries/TemporalQueryMessageHandler.java
  cineast-core/build.gradle
  cineast-core/src/main/java/org/vitrivr/cineast/core/features/CLIPImage.java
  cineast-core/src/main/java/org/vitrivr/cineast/core/features/CLIPText.java
  cineast-core/src/main/java/org/vitrivr/cineast/core/features/InceptionResnetV2.java
  cineast-core/src/main/java/org/vitrivr/cineast/core/features/VisualTextCoEmbedding.java
  cineast-core/src/main/java/org/vitrivr/cineast/core/util/text/ClipTokenizer.java
  cineast-runtime/build.gradle
  cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/CliUtils.java
  cineast-runtime/src/main/java/org/vitrivr/cineast/standalone/cli/TextRetrievalCommand.java
Labels: bug, implementation, waiting-for-approval

#340 Fix Docker cmd
  README.md
Labels: waiting-for-approval

#350 Fixing CLI not exiting properly
  cineast-api/src/main/java/org/vitrivr/cineast/api/Main.java
Labels: bug, waiting-for-approval
